// Date: 12/13/2013 11:38:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package gruntpie224.wintercraft.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSantaHat extends ModelBiped
{
  //fields
	ModelRenderer hatbrim;
    ModelRenderer hat1;
    ModelRenderer hat2;
    ModelRenderer hat3;
    ModelRenderer hat4;
    ModelRenderer hat5;
    ModelRenderer hat6;
    ModelRenderer hatpoof;
  
  public ModelSantaHat(float f)
  {
	super(f);
	textureWidth = 64;
    textureHeight = 128;
    
      hatbrim = new ModelRenderer(this, 25, 2);
      hatbrim.addBox(0F, 0F, 0F, 7, 1, 8);
      hatbrim.setRotationPoint(-3.5F, -9.0F, -4F);
      hatbrim.setTextureSize(64, 128);
   	  hatbrim.mirror = true;
   	  setRotation(hatbrim, -0.122173F, 0F, 0F);
      hat1 = new ModelRenderer(this, 0, 0);
      hat1.addBox(0F, 0F, 0F, 6, 3, 6);
      hat1.setRotationPoint(-3F, -12F, -2.6F);
      hat1.setTextureSize(64, 128);
      hat1.mirror = true;
      setRotation(hat1, -0.1745329F, 0F, 0F);
      hat2 = new ModelRenderer(this, 0, 0);
      hat2.addBox(0F, 0F, 0F, 5, 3, 5);
      hat2.setRotationPoint(-2.5F, -13.8F, -1.1F);
      hat2.setTextureSize(64, 128);
      hat2.mirror = true;
      setRotation(hat2, -0.5410521F, 0F, 0F);
      hat3 = new ModelRenderer(this, 0, 0);
      hat3.addBox(0F, 0F, 0F, 4, 3, 4);
      hat3.setRotationPoint(-2F, -14.666667F, 1F);
      hat3.setTextureSize(64, 128);
      hat3.mirror = true;
      setRotation(hat3, -0.6981317F, 0F, 0F);
      hat4 = new ModelRenderer(this, 0, 0);
      hat4.addBox(0F, 0F, 0F, 3, 2, 3);
      hat4.setRotationPoint(-1.5F, -15.5F, 2.5F);
      hat4.setTextureSize(64, 128);
      hat4.mirror = true;
      setRotation(hat4, -0.9948377F, 0F, 0F);
      hat5 = new ModelRenderer(this, 0, 0);
      hat5.addBox(0F, 0F, 0F, 2, 3, 2);
      hat5.setRotationPoint(-1F, -16F, 4.4F);
      hat5.setTextureSize(64, 128);
      hat5.mirror = true;
      setRotation(hat5, -1.012291F, 0F, 0F);
      hat6 = new ModelRenderer(this, 0, 0);
      hat6.addBox(0F, 0F, 0F, 1, 2, 1);
      hat6.setRotationPoint(-0.5F, -16F, 6F);
      hat6.setTextureSize(64, 128);
      hat6.mirror = true;
      setRotation(hat6, -1.27409F, 0F, 0F);
      hatpoof = new ModelRenderer(this, 0, 39);
      hatpoof.addBox(0F, 0F, 0F, 2, 2, 2);
      hatpoof.setRotationPoint(-1F, -16.5F, 5.6F);
      hatpoof.setTextureSize(64, 128);
      hatpoof.mirror = true;
      setRotation(hatpoof, 0F, 0F, 0F);
      
      this.bipedHead.addChild(hatbrim);
      this.bipedHead.addChild(hat1);
      this.bipedHead.addChild(hat2);
      this.bipedHead.addChild(hat3);
      this.bipedHead.addChild(hat4);
      this.bipedHead.addChild(hat5);
      this.bipedHead.addChild(hat6);
      this.bipedHead.addChild(hatpoof);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
  
	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}