/*
*** MADE BY MRPONYCAPTAIN'S .SCHEMATIC TO .JAVA CONVERTING TOOL v2.0 ***
*/
package wintercraft.worldgen.structure;

import java.util.Random;

import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemDoor;
import net.minecraft.util.MathHelper;
import net.minecraft.world.World;
import net.minecraft.world.chunk.IChunkProvider;
import net.minecraft.world.gen.feature.WorldGenerator;
import wintercraft.blocks.WinterBlocks;
import wintercraft.blocks.WinterSpecialBlocks;
import wintercraft.entity.passive.EntityElf;
import wintercraft.helper.FeatureConfig;
import cpw.mods.fml.common.IWorldGenerator;

public class StructureElfHouse extends WorldGenerator implements IWorldGenerator
{
	protected Block[] GetValidSpawnBlocks() {
		return new Block[] {
			Blocks.grass,
			Blocks.dirt,
			Blocks.snow,
			Blocks.snow_layer
		};
	}

	public boolean LocationIsValidSpawn(World world, int i, int j, int k){
		int distanceToAir = 0;
		Block checkID = world.getBlock(i, j, k);

		while (checkID != Blocks.air){
			distanceToAir++;
			checkID = world.getBlock(i, j + distanceToAir, k);
		}

		if (distanceToAir > 3){
			return false;
		}
		j += distanceToAir - 1;

		Block blockID = world.getBlock(i, j, k);
		Block blockIDAbove = world.getBlock(i, j+1, k);
		Block blockIDBelow = world.getBlock(i, j-1, k);
		for (Block x : GetValidSpawnBlocks()){
			if (blockIDAbove != Blocks.air){
				return false;
			}
			if (blockID == x){
				return true;
			}else if (blockID == Blocks.snow && blockIDBelow == x){
				return true;
			}
		}
		return false;
	}

	public StructureElfHouse() { }

	@Override
	public void generate(Random random, int chunkX, int chunkZ, World world, IChunkProvider chunkGenerator, IChunkProvider chunkProvider) { }

	public boolean generate(World world, Random rand, int i, int j, int k) {
		//check that each corner is one of the valid spawn blocks
		if(!LocationIsValidSpawn(world, i, j, k) || !LocationIsValidSpawn(world, i + 8, j, k) || !LocationIsValidSpawn(world, i + 8, j, k + 8) || !LocationIsValidSpawn(world, i, j, k + 8))
		{
			return false;
		}
		
		if(FeatureConfig.showSpawnLocation){
			System.out.println("Elf House X:" + i);
	 		System.out.println("Elf House Z:" + k);
		}
		
		k = k - 10;
		i = i - 10;
		j += -1;
		world.setBlock(i + 0, j + 0, k + 0, Blocks.grass);
		world.setBlock(i + 0, j + 0, k + 1, Blocks.grass);
		world.setBlock(i + 0, j + 0, k + 2, Blocks.grass);
		world.setBlock(i + 0, j + 0, k + 3, Blocks.grass);
		world.setBlock(i + 0, j + 0, k + 4, Blocks.grass);
		world.setBlock(i + 0, j + 0, k + 5, Blocks.grass);
		world.setBlock(i + 0, j + 0, k + 6, Blocks.grass);
		world.setBlock(i + 0, j + 0, k + 7, Blocks.grass);
		world.setBlock(i + 0, j + 0, k + 8, Blocks.grass);
		world.setBlock(i + 0, j + 1, k + 0, Blocks.air);
		world.setBlock(i + 0, j + 1, k + 1, Blocks.air);
		world.setBlock(i + 0, j + 1, k + 2, Blocks.air);
		world.setBlock(i + 0, j + 1, k + 3, Blocks.air);
		world.setBlock(i + 0, j + 1, k + 4, Blocks.air);
		world.setBlock(i + 0, j + 1, k + 5, Blocks.air);
		world.setBlock(i + 0, j + 1, k + 6, Blocks.air);
		world.setBlock(i + 0, j + 1, k + 7, Blocks.air);
		world.setBlock(i + 0, j + 1, k + 8, Blocks.air);
		world.setBlock(i + 0, j + 2, k + 0, Blocks.air);
		world.setBlock(i + 0, j + 2, k + 1, Blocks.air);
		world.setBlock(i + 0, j + 2, k + 2, Blocks.air);
		world.setBlock(i + 0, j + 2, k + 3, Blocks.air);
		world.setBlock(i + 0, j + 2, k + 4, Blocks.air);
		world.setBlock(i + 0, j + 2, k + 5, Blocks.air);
		world.setBlock(i + 0, j + 2, k + 6, Blocks.air);
		world.setBlock(i + 0, j + 2, k + 7, Blocks.air);
		world.setBlock(i + 0, j + 2, k + 8, Blocks.air);
		world.setBlock(i + 0, j + 3, k + 0, Blocks.air);
		world.setBlock(i + 0, j + 3, k + 1, Blocks.air);
		world.setBlock(i + 0, j + 3, k + 2, Blocks.air);
		world.setBlock(i + 0, j + 3, k + 3, Blocks.air);
		world.setBlock(i + 0, j + 3, k + 4, Blocks.air);
		world.setBlock(i + 0, j + 3, k + 5, Blocks.air);
		world.setBlock(i + 0, j + 3, k + 6, Blocks.air);
		world.setBlock(i + 0, j + 3, k + 7, Blocks.air);
		world.setBlock(i + 0, j + 3, k + 8, Blocks.air);
		world.setBlock(i + 0, j + 4, k + 0, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 0, j + 4, k + 1, Blocks.air);
		world.setBlock(i + 0, j + 4, k + 2, Blocks.air);
		world.setBlock(i + 0, j + 4, k + 3, Blocks.air);
		world.setBlock(i + 0, j + 4, k + 4, Blocks.air);
		world.setBlock(i + 0, j + 4, k + 5, Blocks.air);
		world.setBlock(i + 0, j + 4, k + 6, Blocks.air);
		world.setBlock(i + 0, j + 4, k + 7, Blocks.air);
		world.setBlock(i + 0, j + 4, k + 8, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 0, j + 5, k + 0, Blocks.air);
		world.setBlock(i + 0, j + 5, k + 1, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 0, j + 5, k + 2, Blocks.air);
		world.setBlock(i + 0, j + 5, k + 3, Blocks.air);
		world.setBlock(i + 0, j + 5, k + 4, Blocks.air);
		world.setBlock(i + 0, j + 5, k + 5, Blocks.air);
		world.setBlock(i + 0, j + 5, k + 6, Blocks.air);
		world.setBlock(i + 0, j + 5, k + 7, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 0, j + 5, k + 8, Blocks.air);
		world.setBlock(i + 0, j + 6, k + 0, Blocks.air);
		world.setBlock(i + 0, j + 6, k + 1, Blocks.air);
		world.setBlock(i + 0, j + 6, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 0, j + 6, k + 3, Blocks.air);
		world.setBlock(i + 0, j + 6, k + 4, Blocks.air);
		world.setBlock(i + 0, j + 6, k + 5, Blocks.air);
		world.setBlock(i + 0, j + 6, k + 6, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 0, j + 6, k + 7, Blocks.air);
		world.setBlock(i + 0, j + 6, k + 8, Blocks.air);
		world.setBlock(i + 0, j + 7, k + 0, Blocks.air);
		world.setBlock(i + 0, j + 7, k + 1, Blocks.air);
		world.setBlock(i + 0, j + 7, k + 2, Blocks.air);
		world.setBlock(i + 0, j + 7, k + 3, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 0, j + 7, k + 4, Blocks.air);
		world.setBlock(i + 0, j + 7, k + 5, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 0, j + 7, k + 6, Blocks.air);
		world.setBlock(i + 0, j + 7, k + 7, Blocks.air);
		world.setBlock(i + 0, j + 7, k + 8, Blocks.air);
		world.setBlock(i + 0, j + 8, k + 0, Blocks.air);
		world.setBlock(i + 0, j + 8, k + 1, Blocks.air);
		world.setBlock(i + 0, j + 8, k + 2, Blocks.air);
		world.setBlock(i + 0, j + 8, k + 3, Blocks.air);
		world.setBlock(i + 0, j + 8, k + 4, WinterBlocks.singleSnowSlab);
		world.setBlock(i + 0, j + 8, k + 5, Blocks.air);
		world.setBlock(i + 0, j + 8, k + 6, Blocks.air);
		world.setBlock(i + 0, j + 8, k + 7, Blocks.air);
		world.setBlock(i + 0, j + 8, k + 8, Blocks.air);
		world.setBlock(i + 0, j + 9, k + 0, Blocks.air);
		world.setBlock(i + 0, j + 9, k + 1, Blocks.air);
		world.setBlock(i + 0, j + 9, k + 2, Blocks.air);
		world.setBlock(i + 0, j + 9, k + 3, Blocks.air);
		world.setBlock(i + 0, j + 9, k + 4, Blocks.air);
		world.setBlock(i + 0, j + 9, k + 5, Blocks.air);
		world.setBlock(i + 0, j + 9, k + 6, Blocks.air);
		world.setBlock(i + 0, j + 9, k + 7, Blocks.air);
		world.setBlock(i + 0, j + 9, k + 8, Blocks.air);
		world.setBlock(i + 1, j + 0, k + 0, Blocks.grass);
		world.setBlock(i + 1, j + 0, k + 1, Blocks.dirt);
		world.setBlock(i + 1, j + 0, k + 2, Blocks.dirt);
		world.setBlock(i + 1, j + 0, k + 3, Blocks.dirt);
		world.setBlock(i + 1, j + 0, k + 4, WinterBlocks.icedStone);
		world.setBlock(i + 1, j + 0, k + 5, Blocks.dirt);
		world.setBlock(i + 1, j + 0, k + 6, Blocks.dirt);
		world.setBlock(i + 1, j + 0, k + 7, Blocks.dirt);
		world.setBlock(i + 1, j + 0, k + 8, Blocks.grass);
		world.setBlock(i + 1, j + 1, k + 0, Blocks.air);
		world.setBlock(i + 1, j + 1, k + 1, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 1, j + 1, k + 2, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 1, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 1, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 1, k + 6, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 1, k + 7, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 1, j + 1, k + 8, Blocks.air);
		world.setBlock(i + 1, j + 2, k + 0, Blocks.air);
		world.setBlock(i + 1, j + 2, k + 1, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 1, j + 2, k + 2, WinterBlocks.winterIce);
		world.setBlock(i + 1, j + 2, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 2, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 2, k + 6, WinterBlocks.winterIce);
		world.setBlock(i + 1, j + 2, k + 7, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 1, j + 2, k + 8, Blocks.air);
		world.setBlock(i + 1, j + 3, k + 0, Blocks.air);
		world.setBlock(i + 1, j + 3, k + 1, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 1, j + 3, k + 2, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 3, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 3, k + 4, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 3, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 3, k + 6, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 3, k + 7, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 1, j + 3, k + 8, Blocks.air);
		world.setBlock(i + 1, j + 4, k + 0, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 1, j + 4, k + 1, WinterBlocks.candyCaneBlock, 4, 2);
		world.setBlock(i + 1, j + 4, k + 2, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 4, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 4, k + 4, WinterBlocks.winterIce);
		world.setBlock(i + 1, j + 4, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 4, k + 6, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 4, k + 7, WinterBlocks.candyCaneBlock, 4, 2);
		world.setBlock(i + 1, j + 4, k + 8, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 1, j + 5, k + 0, Blocks.air);
		world.setBlock(i + 1, j + 5, k + 1, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 1, j + 5, k + 2, Blocks.snow);
		world.setBlock(i + 1, j + 5, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 5, k + 4, WinterBlocks.winterIce);
		world.setBlock(i + 1, j + 5, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 5, k + 6, Blocks.snow);
		world.setBlock(i + 1, j + 5, k + 7, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 1, j + 5, k + 8, Blocks.air);
		world.setBlock(i + 1, j + 6, k + 0, Blocks.air);
		world.setBlock(i + 1, j + 6, k + 1, Blocks.air);
		world.setBlock(i + 1, j + 6, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 1, j + 6, k + 3, Blocks.snow);
		world.setBlock(i + 1, j + 6, k + 4, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 1, j + 6, k + 5, Blocks.snow);
		world.setBlock(i + 1, j + 6, k + 6, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 1, j + 6, k + 7, Blocks.air);
		world.setBlock(i + 1, j + 6, k + 8, Blocks.air);
		world.setBlock(i + 1, j + 7, k + 0, Blocks.air);
		world.setBlock(i + 1, j + 7, k + 1, Blocks.air);
		world.setBlock(i + 1, j + 7, k + 2, Blocks.air);
		world.setBlock(i + 1, j + 7, k + 3, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 1, j + 7, k + 4, Blocks.snow);
		world.setBlock(i + 1, j + 7, k + 5, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 1, j + 7, k + 6, Blocks.air);
		world.setBlock(i + 1, j + 7, k + 7, Blocks.air);
		world.setBlock(i + 1, j + 7, k + 8, Blocks.air);
		world.setBlock(i + 1, j + 8, k + 0, Blocks.air);
		world.setBlock(i + 1, j + 8, k + 1, Blocks.air);
		world.setBlock(i + 1, j + 8, k + 2, Blocks.air);
		world.setBlock(i + 1, j + 8, k + 3, Blocks.air);
		world.setBlock(i + 1, j + 8, k + 4, WinterBlocks.singleSnowSlab);
		world.setBlock(i + 1, j + 8, k + 5, Blocks.air);
		world.setBlock(i + 1, j + 8, k + 6, Blocks.air);
		world.setBlock(i + 1, j + 8, k + 7, Blocks.air);
		world.setBlock(i + 1, j + 8, k + 8, Blocks.air);
		world.setBlock(i + 1, j + 9, k + 0, Blocks.air);
		world.setBlock(i + 1, j + 9, k + 1, Blocks.air);
		world.setBlock(i + 1, j + 9, k + 2, Blocks.air);
		world.setBlock(i + 1, j + 9, k + 3, Blocks.air);
		world.setBlock(i + 1, j + 9, k + 4, Blocks.air);
		world.setBlock(i + 1, j + 9, k + 5, Blocks.air);
		world.setBlock(i + 1, j + 9, k + 6, Blocks.air);
		world.setBlock(i + 1, j + 9, k + 7, Blocks.air);
		world.setBlock(i + 1, j + 9, k + 8, Blocks.air);
		world.setBlock(i + 2, j + 0, k + 0, Blocks.grass);
		world.setBlock(i + 2, j + 0, k + 1, Blocks.dirt);
		world.setBlock(i + 2, j + 0, k + 2, WinterBlocks.icedStone);
		world.setBlock(i + 2, j + 0, k + 3, WinterBlocks.icedStone);
		world.setBlock(i + 2, j + 0, k + 4, WinterBlocks.icedStone);
		world.setBlock(i + 2, j + 0, k + 5, WinterBlocks.icedStone);
		world.setBlock(i + 2, j + 0, k + 6, WinterBlocks.icedStone);
		world.setBlock(i + 2, j + 0, k + 7, Blocks.dirt);
		world.setBlock(i + 2, j + 0, k + 8, Blocks.grass);
		world.setBlock(i + 2, j + 1, k + 0, Blocks.air);
		world.setBlock(i + 2, j + 1, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 2, j + 1, k + 2, WinterBlocks.freezer);
		world.setBlock(i + 2, j + 1, k + 3, Blocks.air);
		world.setBlock(i + 2, j + 1, k + 4, Blocks.air);
		world.setBlock(i + 2, j + 1, k + 5, Blocks.air);
		world.setBlock(i + 2, j + 1, k + 6, Blocks.air);
		world.setBlock(i + 2, j + 1, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 2, j + 1, k + 8, Blocks.air);
		world.setBlock(i + 2, j + 2, k + 0, Blocks.air);
		world.setBlock(i + 2, j + 2, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 2, j + 2, k + 2, WinterBlocks.snowGlobeBlock);
		world.setBlock(i + 2, j + 2, k + 3, Blocks.air);
		world.setBlock(i + 2, j + 2, k + 4, Blocks.air);
		world.setBlock(i + 2, j + 2, k + 5, Blocks.air);
		world.setBlock(i + 2, j + 2, k + 6, Blocks.air);
		world.setBlock(i + 2, j + 2, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 2, j + 2, k + 8, Blocks.air);
		world.setBlock(i + 2, j + 3, k + 0, Blocks.air);
		world.setBlock(i + 2, j + 3, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 2, j + 3, k + 2, Blocks.air);
		world.setBlock(i + 2, j + 3, k + 3, Blocks.air);
		world.setBlock(i + 2, j + 3, k + 4, Blocks.air);
		world.setBlock(i + 2, j + 3, k + 5, Blocks.air);
		world.setBlock(i + 2, j + 3, k + 6, Blocks.air);
		world.setBlock(i + 2, j + 3, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 2, j + 3, k + 8, Blocks.air);
		world.setBlock(i + 2, j + 4, k + 0, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 2, j + 4, k + 1, WinterBlocks.snowBrick);
		world.setBlock(i + 2, j + 4, k + 2, Blocks.air);
		world.setBlock(i + 2, j + 4, k + 3, Blocks.air);
		world.setBlock(i + 2, j + 4, k + 4, Blocks.air);
		world.setBlock(i + 2, j + 4, k + 5, Blocks.air);
		world.setBlock(i + 2, j + 4, k + 6, Blocks.air);
		world.setBlock(i + 2, j + 4, k + 7, WinterBlocks.snowBrick);
		world.setBlock(i + 2, j + 4, k + 8, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 2, j + 5, k + 0, Blocks.air);
		world.setBlock(i + 2, j + 5, k + 1, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 2, j + 5, k + 2, WinterBlocks.snowBrick);
		world.setBlock(i + 2, j + 5, k + 3, Blocks.air);
		world.setBlock(i + 2, j + 5, k + 4, Blocks.air);
		world.setBlock(i + 2, j + 5, k + 5, Blocks.air);
		world.setBlock(i + 2, j + 5, k + 6, WinterBlocks.snowBrick);
		world.setBlock(i + 2, j + 5, k + 7, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 2, j + 5, k + 8, Blocks.air);
		world.setBlock(i + 2, j + 6, k + 0, Blocks.air);
		world.setBlock(i + 2, j + 6, k + 1, Blocks.air);
		world.setBlock(i + 2, j + 6, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 2, j + 6, k + 3, Blocks.air);
		world.setBlock(i + 2, j + 6, k + 4, Blocks.air);
		world.setBlock(i + 2, j + 6, k + 5, Blocks.air);
		world.setBlock(i + 2, j + 6, k + 6, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 2, j + 6, k + 7, Blocks.air);
		world.setBlock(i + 2, j + 6, k + 8, Blocks.air);
		world.setBlock(i + 2, j + 7, k + 0, Blocks.air);
		world.setBlock(i + 2, j + 7, k + 1, Blocks.air);
		world.setBlock(i + 2, j + 7, k + 2, Blocks.air);
		world.setBlock(i + 2, j + 7, k + 3, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 2, j + 7, k + 4, WinterBlocks.snowBrick);
		world.setBlock(i + 2, j + 7, k + 5, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 2, j + 7, k + 6, Blocks.air);
		world.setBlock(i + 2, j + 7, k + 7, Blocks.air);
		world.setBlock(i + 2, j + 7, k + 8, Blocks.air);
		world.setBlock(i + 2, j + 8, k + 0, Blocks.air);
		world.setBlock(i + 2, j + 8, k + 1, Blocks.air);
		world.setBlock(i + 2, j + 8, k + 2, Blocks.air);
		world.setBlock(i + 2, j + 8, k + 3, Blocks.air);
		world.setBlock(i + 2, j + 8, k + 4, WinterBlocks.singleSnowSlab);
		world.setBlock(i + 2, j + 8, k + 5, Blocks.air);
		world.setBlock(i + 2, j + 8, k + 6, Blocks.air);
		world.setBlock(i + 2, j + 8, k + 7, Blocks.air);
		world.setBlock(i + 2, j + 8, k + 8, Blocks.air);
		world.setBlock(i + 2, j + 9, k + 0, Blocks.air);
		world.setBlock(i + 2, j + 9, k + 1, Blocks.air);
		world.setBlock(i + 2, j + 9, k + 2, Blocks.air);
		world.setBlock(i + 2, j + 9, k + 3, Blocks.air);
		world.setBlock(i + 2, j + 9, k + 4, Blocks.air);
		world.setBlock(i + 2, j + 9, k + 5, Blocks.air);
		world.setBlock(i + 2, j + 9, k + 6, Blocks.air);
		world.setBlock(i + 2, j + 9, k + 7, Blocks.air);
		world.setBlock(i + 2, j + 9, k + 8, Blocks.air);
		world.setBlock(i + 3, j + 0, k + 0, Blocks.grass);
		world.setBlock(i + 3, j + 0, k + 1, Blocks.dirt);
		world.setBlock(i + 3, j + 0, k + 2, WinterBlocks.icedStone);
		world.setBlock(i + 3, j + 0, k + 3, WinterBlocks.icedStone);
		world.setBlock(i + 3, j + 0, k + 4, WinterBlocks.icedStone);
		world.setBlock(i + 3, j + 0, k + 5, WinterBlocks.icedStone);
		world.setBlock(i + 3, j + 0, k + 6, WinterBlocks.icedStone);
		world.setBlock(i + 3, j + 0, k + 7, Blocks.dirt);
		world.setBlock(i + 3, j + 0, k + 8, Blocks.grass);
		world.setBlock(i + 3, j + 1, k + 0, Blocks.air);
		world.setBlock(i + 3, j + 1, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 3, j + 1, k + 2, Blocks.air);
		world.setBlock(i + 3, j + 1, k + 3, Blocks.air);
		world.setBlock(i + 3, j + 1, k + 4, Blocks.air);
		world.setBlock(i + 3, j + 1, k + 5, Blocks.air);
		world.setBlock(i + 3, j + 1, k + 6, Blocks.air);
		world.setBlock(i + 3, j + 1, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 3, j + 1, k + 8, Blocks.air);
		world.setBlock(i + 3, j + 2, k + 0, Blocks.air);
		world.setBlock(i + 3, j + 2, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 3, j + 2, k + 2, Blocks.air);
		world.setBlock(i + 3, j + 2, k + 3, Blocks.air);
		world.setBlock(i + 3, j + 2, k + 4, Blocks.air);
		world.setBlock(i + 3, j + 2, k + 5, Blocks.air);
		world.setBlock(i + 3, j + 2, k + 6, Blocks.air);
		world.setBlock(i + 3, j + 2, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 3, j + 2, k + 8, Blocks.air);
		world.setBlock(i + 3, j + 3, k + 0, Blocks.air);
		world.setBlock(i + 3, j + 3, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 3, j + 3, k + 2, Blocks.air);
		world.setBlock(i + 3, j + 3, k + 3, Blocks.air);
		world.setBlock(i + 3, j + 3, k + 4, Blocks.air);
		world.setBlock(i + 3, j + 3, k + 5, Blocks.air);
		world.setBlock(i + 3, j + 3, k + 6, Blocks.air);
		world.setBlock(i + 3, j + 3, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 3, j + 3, k + 8, Blocks.air);
		world.setBlock(i + 3, j + 4, k + 0, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 3, j + 4, k + 1, WinterBlocks.snowBrick);
		world.setBlock(i + 3, j + 4, k + 2, Blocks.air);
		world.setBlock(i + 3, j + 4, k + 3, Blocks.air);
		world.setBlock(i + 3, j + 4, k + 4, Blocks.air);
		world.setBlock(i + 3, j + 4, k + 5, Blocks.air);
		world.setBlock(i + 3, j + 4, k + 6, Blocks.air);
		world.setBlock(i + 3, j + 4, k + 7, WinterBlocks.snowBrick);
		world.setBlock(i + 3, j + 4, k + 8, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 3, j + 5, k + 0, Blocks.air);
		world.setBlock(i + 3, j + 5, k + 1, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 3, j + 5, k + 2, WinterBlocks.snowBrick);
		world.setBlock(i + 3, j + 5, k + 3, Blocks.air);
		world.setBlock(i + 3, j + 5, k + 4, Blocks.air);
		world.setBlock(i + 3, j + 5, k + 5, Blocks.air);
		world.setBlock(i + 3, j + 5, k + 6, WinterBlocks.snowBrick);
		world.setBlock(i + 3, j + 5, k + 7, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 3, j + 5, k + 8, Blocks.air);
		world.setBlock(i + 3, j + 6, k + 0, Blocks.air);
		world.setBlock(i + 3, j + 6, k + 1, Blocks.air);
		world.setBlock(i + 3, j + 6, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 3, j + 6, k + 3, WinterBlocks.candyCaneBlock, 8, 2);
		world.setBlock(i + 3, j + 6, k + 4, WinterBlocks.candyCaneBlock, 8, 2);
		world.setBlock(i + 3, j + 6, k + 5, WinterBlocks.candyCaneBlock, 8, 2);
		world.setBlock(i + 3, j + 6, k + 6, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 3, j + 6, k + 7, Blocks.air);
		world.setBlock(i + 3, j + 6, k + 8, Blocks.air);
		world.setBlock(i + 3, j + 7, k + 0, Blocks.air);
		world.setBlock(i + 3, j + 7, k + 1, Blocks.air);
		world.setBlock(i + 3, j + 7, k + 2, Blocks.air);
		world.setBlock(i + 3, j + 7, k + 3, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 3, j + 7, k + 4, WinterBlocks.snowBrick);
		world.setBlock(i + 3, j + 7, k + 5, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 3, j + 7, k + 6, Blocks.air);
		world.setBlock(i + 3, j + 7, k + 7, Blocks.air);
		world.setBlock(i + 3, j + 7, k + 8, Blocks.air);
		world.setBlock(i + 3, j + 8, k + 0, Blocks.air);
		world.setBlock(i + 3, j + 8, k + 1, Blocks.air);
		world.setBlock(i + 3, j + 8, k + 2, Blocks.air);
		world.setBlock(i + 3, j + 8, k + 3, Blocks.air);
		world.setBlock(i + 3, j + 8, k + 4, WinterBlocks.singleSnowSlab);
		world.setBlock(i + 3, j + 8, k + 5, Blocks.air);
		world.setBlock(i + 3, j + 8, k + 6, Blocks.air);
		world.setBlock(i + 3, j + 8, k + 7, Blocks.air);
		world.setBlock(i + 3, j + 8, k + 8, Blocks.air);
		world.setBlock(i + 3, j + 9, k + 0, Blocks.air);
		world.setBlock(i + 3, j + 9, k + 1, Blocks.air);
		world.setBlock(i + 3, j + 9, k + 2, Blocks.air);
		world.setBlock(i + 3, j + 9, k + 3, Blocks.air);
		world.setBlock(i + 3, j + 9, k + 4, Blocks.air);
		world.setBlock(i + 3, j + 9, k + 5, Blocks.air);
		world.setBlock(i + 3, j + 9, k + 6, Blocks.air);
		world.setBlock(i + 3, j + 9, k + 7, Blocks.air);
		world.setBlock(i + 3, j + 9, k + 8, Blocks.air);
		world.setBlock(i + 4, j + 0, k + 0, Blocks.grass);
		world.setBlock(i + 4, j + 0, k + 1, Blocks.dirt);
		world.setBlock(i + 4, j + 0, k + 2, WinterBlocks.icedStone);
		world.setBlock(i + 4, j + 0, k + 3, WinterBlocks.icedStone);
		world.setBlock(i + 4, j + 0, k + 4, WinterBlocks.icedStone);
		world.setBlock(i + 4, j + 0, k + 5, WinterBlocks.icedStone);
		world.setBlock(i + 4, j + 0, k + 6, WinterBlocks.icedStone);
		world.setBlock(i + 4, j + 0, k + 7, Blocks.dirt);
		world.setBlock(i + 4, j + 0, k + 8, Blocks.grass);
		world.setBlock(i + 4, j + 1, k + 0, Blocks.air);
		world.setBlock(i + 4, j + 1, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 4, j + 1, k + 2, Blocks.air);
		world.setBlock(i + 4, j + 1, k + 3, Blocks.air);
		world.setBlock(i + 4, j + 1, k + 4, Blocks.air);
		world.setBlock(i + 4, j + 1, k + 5, Blocks.air);
		world.setBlock(i + 4, j + 1, k + 6, Blocks.air);
		world.setBlock(i + 4, j + 1, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 4, j + 1, k + 8, Blocks.air);
		world.setBlock(i + 4, j + 2, k + 0, Blocks.air);
		world.setBlock(i + 4, j + 2, k + 1, WinterBlocks.winterIce);
		world.setBlock(i + 4, j + 2, k + 2, Blocks.air);
		world.setBlock(i + 4, j + 2, k + 3, Blocks.air);
		world.setBlock(i + 4, j + 2, k + 4, Blocks.air);
		world.setBlock(i + 4, j + 2, k + 5, Blocks.air);
		world.setBlock(i + 4, j + 2, k + 6, Blocks.air);
		world.setBlock(i + 4, j + 2, k + 7, WinterBlocks.winterIce);
		world.setBlock(i + 4, j + 2, k + 8, Blocks.air);
		world.setBlock(i + 4, j + 3, k + 0, Blocks.air);
		world.setBlock(i + 4, j + 3, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 4, j + 3, k + 2, Blocks.air);
		world.setBlock(i + 4, j + 3, k + 3, Blocks.air);
		world.setBlock(i + 4, j + 3, k + 4, Blocks.air);
		world.setBlock(i + 4, j + 3, k + 5, Blocks.air);
		world.setBlock(i + 4, j + 3, k + 6, Blocks.air);
		world.setBlock(i + 4, j + 3, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 4, j + 3, k + 8, Blocks.air);
		world.setBlock(i + 4, j + 4, k + 0, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 4, j + 4, k + 1, WinterBlocks.snowBrick);
		world.setBlock(i + 4, j + 4, k + 2, Blocks.air);
		world.setBlock(i + 4, j + 4, k + 3, Blocks.air);
		world.setBlock(i + 4, j + 4, k + 4, Blocks.air);
		world.setBlock(i + 4, j + 4, k + 5, Blocks.air);
		world.setBlock(i + 4, j + 4, k + 6, Blocks.air);
		world.setBlock(i + 4, j + 4, k + 7, WinterBlocks.snowBrick);
		world.setBlock(i + 4, j + 4, k + 8, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 4, j + 5, k + 0, Blocks.air);
		world.setBlock(i + 4, j + 5, k + 1, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 4, j + 5, k + 2, WinterBlocks.snowBrick);
		world.setBlock(i + 4, j + 5, k + 3, Blocks.air);
		world.setBlock(i + 4, j + 5, k + 4, Blocks.air);
		world.setBlock(i + 4, j + 5, k + 5, Blocks.air);
		world.setBlock(i + 4, j + 5, k + 6, WinterBlocks.snowBrick);
		world.setBlock(i + 4, j + 5, k + 7, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 4, j + 5, k + 8, Blocks.air);
		world.setBlock(i + 4, j + 6, k + 0, Blocks.air);
		world.setBlock(i + 4, j + 6, k + 1, Blocks.air);
		world.setBlock(i + 4, j + 6, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 4, j + 6, k + 3, Blocks.air);
		world.setBlock(i + 4, j + 6, k + 4, Blocks.air);
		world.setBlock(i + 4, j + 6, k + 5, Blocks.air);
		world.setBlock(i + 4, j + 6, k + 6, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 4, j + 6, k + 7, Blocks.air);
		world.setBlock(i + 4, j + 6, k + 8, Blocks.air);
		world.setBlock(i + 4, j + 7, k + 0, Blocks.air);
		world.setBlock(i + 4, j + 7, k + 1, Blocks.air);
		world.setBlock(i + 4, j + 7, k + 2, Blocks.air);
		world.setBlock(i + 4, j + 7, k + 3, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 4, j + 7, k + 4, WinterBlocks.snowBrick);
		world.setBlock(i + 4, j + 7, k + 5, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 4, j + 7, k + 6, Blocks.air);
		world.setBlock(i + 4, j + 7, k + 7, Blocks.air);
		world.setBlock(i + 4, j + 7, k + 8, Blocks.air);
		world.setBlock(i + 4, j + 8, k + 0, Blocks.air);
		world.setBlock(i + 4, j + 8, k + 1, Blocks.air);
		world.setBlock(i + 4, j + 8, k + 2, Blocks.air);
		world.setBlock(i + 4, j + 8, k + 3, Blocks.air);
		world.setBlock(i + 4, j + 8, k + 4, WinterBlocks.singleSnowSlab);
		world.setBlock(i + 4, j + 8, k + 5, Blocks.air);
		world.setBlock(i + 4, j + 8, k + 6, Blocks.air);
		world.setBlock(i + 4, j + 8, k + 7, Blocks.air);
		world.setBlock(i + 4, j + 8, k + 8, Blocks.air);
		world.setBlock(i + 4, j + 9, k + 0, Blocks.air);
		world.setBlock(i + 4, j + 9, k + 1, Blocks.air);
		world.setBlock(i + 4, j + 9, k + 2, Blocks.air);
		world.setBlock(i + 4, j + 9, k + 3, Blocks.air);
		world.setBlock(i + 4, j + 9, k + 4, Blocks.air);
		world.setBlock(i + 4, j + 9, k + 5, Blocks.air);
		world.setBlock(i + 4, j + 9, k + 6, Blocks.air);
		world.setBlock(i + 4, j + 9, k + 7, Blocks.air);
		world.setBlock(i + 4, j + 9, k + 8, Blocks.air);
		world.setBlock(i + 5, j + 0, k + 0, Blocks.grass);
		world.setBlock(i + 5, j + 0, k + 1, Blocks.dirt);
		world.setBlock(i + 5, j + 0, k + 2, WinterBlocks.icedStone);
		world.setBlock(i + 5, j + 0, k + 3, WinterBlocks.icedStone);
		world.setBlock(i + 5, j + 0, k + 4, WinterBlocks.icedStone);
		world.setBlock(i + 5, j + 0, k + 5, WinterBlocks.icedStone);
		world.setBlock(i + 5, j + 0, k + 6, WinterBlocks.icedStone);
		world.setBlock(i + 5, j + 0, k + 7, Blocks.dirt);
		world.setBlock(i + 5, j + 0, k + 8, Blocks.grass);
		world.setBlock(i + 5, j + 1, k + 0, Blocks.air);
		world.setBlock(i + 5, j + 1, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 5, j + 1, k + 2, Blocks.air);
		world.setBlock(i + 5, j + 1, k + 3, Blocks.air);
		world.setBlock(i + 5, j + 1, k + 4, Blocks.air);
		world.setBlock(i + 5, j + 1, k + 5, Blocks.air);
		world.setBlock(i + 5, j + 1, k + 6, Blocks.air);
		world.setBlock(i + 5, j + 1, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 5, j + 1, k + 8, Blocks.air);
		world.setBlock(i + 5, j + 2, k + 0, Blocks.air);
		world.setBlock(i + 5, j + 2, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 5, j + 2, k + 2, Blocks.air);
		world.setBlock(i + 5, j + 2, k + 3, Blocks.air);
		world.setBlock(i + 5, j + 2, k + 4, Blocks.air);
		world.setBlock(i + 5, j + 2, k + 5, Blocks.air);
		world.setBlock(i + 5, j + 2, k + 6, Blocks.air);
		world.setBlock(i + 5, j + 2, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 5, j + 2, k + 8, Blocks.air);
		world.setBlock(i + 5, j + 3, k + 0, Blocks.air);
		world.setBlock(i + 5, j + 3, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 5, j + 3, k + 2, Blocks.air);
		world.setBlock(i + 5, j + 3, k + 4, Blocks.air);
		world.setBlock(i + 5, j + 3, k + 5, Blocks.air);
		world.setBlock(i + 5, j + 3, k + 6, Blocks.air);
		world.setBlock(i + 5, j + 3, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 5, j + 3, k + 8, Blocks.air);
		world.setBlock(i + 5, j + 4, k + 0, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 5, j + 4, k + 1, WinterBlocks.snowBrick);
		world.setBlock(i + 5, j + 4, k + 2, Blocks.air);
		world.setBlock(i + 5, j + 4, k + 3, Blocks.air);
		world.setBlock(i + 5, j + 4, k + 4, Blocks.air);
		world.setBlock(i + 5, j + 4, k + 5, Blocks.air);
		world.setBlock(i + 5, j + 4, k + 6, Blocks.air);
		world.setBlock(i + 5, j + 4, k + 7, WinterBlocks.snowBrick);
		world.setBlock(i + 5, j + 4, k + 8, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 5, j + 5, k + 0, Blocks.air);
		world.setBlock(i + 5, j + 5, k + 1, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 5, j + 5, k + 2, WinterBlocks.snowBrick);
		world.setBlock(i + 5, j + 5, k + 3, Blocks.air);
		world.setBlock(i + 5, j + 5, k + 4, Blocks.air);
		world.setBlock(i + 5, j + 5, k + 5, Blocks.air);
		world.setBlock(i + 5, j + 5, k + 6, WinterBlocks.snowBrick);
		world.setBlock(i + 5, j + 5, k + 7, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 5, j + 5, k + 8, Blocks.air);
		world.setBlock(i + 5, j + 6, k + 0, Blocks.air);
		world.setBlock(i + 5, j + 6, k + 1, Blocks.air);
		world.setBlock(i + 5, j + 6, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 5, j + 6, k + 3, WinterBlocks.candyCaneBlock, 8, 2);
		world.setBlock(i + 5, j + 6, k + 4, WinterBlocks.candyCaneBlock, 8, 2);
		world.setBlock(i + 5, j + 6, k + 5, WinterBlocks.candyCaneBlock, 8, 2);
		world.setBlock(i + 5, j + 6, k + 6, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 5, j + 6, k + 7, Blocks.air);
		world.setBlock(i + 5, j + 6, k + 8, Blocks.air);
		world.setBlock(i + 5, j + 7, k + 0, Blocks.air);
		world.setBlock(i + 5, j + 7, k + 1, Blocks.air);
		world.setBlock(i + 5, j + 7, k + 2, Blocks.air);
		world.setBlock(i + 5, j + 7, k + 3, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 5, j + 7, k + 4, WinterBlocks.snowBrick);
		world.setBlock(i + 5, j + 7, k + 5, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 5, j + 7, k + 6, Blocks.air);
		world.setBlock(i + 5, j + 7, k + 7, Blocks.air);
		world.setBlock(i + 5, j + 7, k + 8, Blocks.air);
		world.setBlock(i + 5, j + 8, k + 0, Blocks.air);
		world.setBlock(i + 5, j + 8, k + 1, Blocks.air);
		world.setBlock(i + 5, j + 8, k + 2, Blocks.air);
		world.setBlock(i + 5, j + 8, k + 3, Blocks.air);
		world.setBlock(i + 5, j + 8, k + 4, WinterBlocks.singleSnowSlab);
		world.setBlock(i + 5, j + 8, k + 5, Blocks.air);
		world.setBlock(i + 5, j + 8, k + 6, Blocks.air);
		world.setBlock(i + 5, j + 8, k + 7, Blocks.air);
		world.setBlock(i + 5, j + 8, k + 8, Blocks.air);
		world.setBlock(i + 5, j + 9, k + 0, Blocks.air);
		world.setBlock(i + 5, j + 9, k + 1, Blocks.air);
		world.setBlock(i + 5, j + 9, k + 2, Blocks.air);
		world.setBlock(i + 5, j + 9, k + 3, Blocks.air);
		world.setBlock(i + 5, j + 9, k + 4, Blocks.air);
		world.setBlock(i + 5, j + 9, k + 5, Blocks.air);
		world.setBlock(i + 5, j + 9, k + 6, Blocks.air);
		world.setBlock(i + 5, j + 9, k + 7, Blocks.air);
		world.setBlock(i + 5, j + 9, k + 8, Blocks.air);
		world.setBlock(i + 6, j + 0, k + 0, Blocks.grass);
		world.setBlock(i + 6, j + 0, k + 1, Blocks.dirt);
		world.setBlock(i + 6, j + 0, k + 2, WinterBlocks.icedStone);
		world.setBlock(i + 6, j + 0, k + 3, WinterBlocks.icedStone);
		world.setBlock(i + 6, j + 0, k + 4, WinterBlocks.icedStone);
		world.setBlock(i + 6, j + 0, k + 5, WinterBlocks.icedStone);
		world.setBlock(i + 6, j + 0, k + 6, WinterBlocks.icedStone);
		world.setBlock(i + 6, j + 0, k + 7, Blocks.dirt);
		world.setBlock(i + 6, j + 0, k + 8, Blocks.grass);
		world.setBlock(i + 6, j + 1, k + 0, Blocks.air);
		world.setBlock(i + 6, j + 1, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 6, j + 1, k + 2, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 1, k + 3, WinterBlocks.fireplaceActive);
		world.setBlock(i + 6, j + 1, k + 4, WinterBlocks.snowBrick);
		int i1 = MathHelper.floor_double((double)(180 * 4.0F / 360.0F) + 0.5D) & 3;
		world.setBlock(i + 6, j + 1, k + 6, Blocks.bed, i1, 3);
		byte b0 = 0;
        byte b1 = 0;

        if (i1 == 0)
        {
            b1 = 1;
        }

        if (i1 == 1)
        {
            b0 = -1;
        }

        if (i1 == 2)
        {
            b1 = -1;
        }

        if (i1 == 3)
        {
            b0 = 1;
        }

		
        if (world.getBlock(i + 6, j + 1, k + 6) == Blocks.bed)
        {
        	world.setBlock(i + 6 + b0, j + 1, k + 6 + b1, Blocks.bed, i1 + 8, 3);
        }
		//world.setBlock(i + 7, j + 1, k + 4, Blocks.bed);
		EntityElf entityElf = new EntityElf(world);
		entityElf.setLocationAndAngles(i + 5, j + 1, k + 5, 0.0F, 0.0F);
		world.spawnEntityInWorld(entityElf);
		world.setBlock(i + 6, j + 1, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 6, j + 1, k + 8, Blocks.air);
		world.setBlock(i + 6, j + 2, k + 0, Blocks.air);
		world.setBlock(i + 6, j + 2, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 6, j + 2, k + 2, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 2, k + 3, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 2, k + 4, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 2, k + 5, Blocks.air);
		world.setBlock(i + 6, j + 2, k + 6, Blocks.air);
		world.setBlock(i + 6, j + 2, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 6, j + 2, k + 8, Blocks.air);
		world.setBlock(i + 6, j + 3, k + 0, Blocks.air);
		world.setBlock(i + 6, j + 3, k + 1, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 6, j + 3, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 6, j + 3, k + 3, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 3, k + 4, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 6, j + 3, k + 5, Blocks.air);
		world.setBlock(i + 6, j + 3, k + 6, Blocks.air);
		world.setBlock(i + 6, j + 3, k + 7, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 6, j + 3, k + 8, Blocks.air);
		world.setBlock(i + 6, j + 4, k + 0, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 6, j + 4, k + 1, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 4, k + 2, Blocks.air);
		world.setBlock(i + 6, j + 4, k + 3, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 4, k + 4, Blocks.air);
		world.setBlock(i + 6, j + 4, k + 5, Blocks.air);
		world.setBlock(i + 6, j + 4, k + 6, Blocks.air);
		world.setBlock(i + 6, j + 4, k + 7, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 4, k + 8, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 6, j + 5, k + 0, Blocks.air);
		world.setBlock(i + 6, j + 5, k + 1, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 6, j + 5, k + 2, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 5, k + 3, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 5, k + 4, Blocks.air);
		world.setBlock(i + 6, j + 5, k + 5, Blocks.air);
		world.setBlock(i + 6, j + 5, k + 6, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 5, k + 7, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 6, j + 5, k + 8, Blocks.air);
		world.setBlock(i + 6, j + 6, k + 0, Blocks.air);
		world.setBlock(i + 6, j + 6, k + 1, Blocks.air);
		world.setBlock(i + 6, j + 6, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 6, j + 6, k + 3, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 6, k + 4, Blocks.air);
		world.setBlock(i + 6, j + 6, k + 5, Blocks.air);
		world.setBlock(i + 6, j + 6, k + 6, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 6, j + 6, k + 7, Blocks.air);
		world.setBlock(i + 6, j + 6, k + 8, Blocks.air);
		world.setBlock(i + 6, j + 7, k + 0, Blocks.air);
		world.setBlock(i + 6, j + 7, k + 1, Blocks.air);
		world.setBlock(i + 6, j + 7, k + 2, Blocks.air);
		world.setBlock(i + 6, j + 7, k + 3, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 7, k + 4, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 7, k + 5, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 6, j + 7, k + 6, Blocks.air);
		world.setBlock(i + 6, j + 7, k + 7, Blocks.air);
		world.setBlock(i + 6, j + 7, k + 8, Blocks.air);
		world.setBlock(i + 6, j + 8, k + 0, Blocks.air);
		world.setBlock(i + 6, j + 8, k + 1, Blocks.air);
		world.setBlock(i + 6, j + 8, k + 2, Blocks.air);
		world.setBlock(i + 6, j + 8, k + 3, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 8, k + 4, WinterBlocks.singleSnowSlab);
		world.setBlock(i + 6, j + 8, k + 5, Blocks.air);
		world.setBlock(i + 6, j + 8, k + 6, Blocks.air);
		world.setBlock(i + 6, j + 8, k + 7, Blocks.air);
		world.setBlock(i + 6, j + 8, k + 8, Blocks.air);
		world.setBlock(i + 6, j + 9, k + 0, Blocks.air);
		world.setBlock(i + 6, j + 9, k + 1, Blocks.air);
		world.setBlock(i + 6, j + 9, k + 2, Blocks.air);
		world.setBlock(i + 6, j + 9, k + 3, WinterBlocks.snowBrick);
		world.setBlock(i + 6, j + 9, k + 4, Blocks.air);
		world.setBlock(i + 6, j + 9, k + 5, Blocks.air);
		world.setBlock(i + 6, j + 9, k + 6, Blocks.air);
		world.setBlock(i + 6, j + 9, k + 7, Blocks.air);
		world.setBlock(i + 6, j + 9, k + 8, Blocks.air);
		world.setBlock(i + 7, j + 0, k + 0, Blocks.grass);
		world.setBlock(i + 7, j + 0, k + 1, Blocks.dirt);
		world.setBlock(i + 7, j + 0, k + 2, Blocks.dirt);
		world.setBlock(i + 7, j + 0, k + 3, Blocks.dirt);
		world.setBlock(i + 7, j + 0, k + 4, Blocks.dirt);
		world.setBlock(i + 7, j + 0, k + 5, Blocks.dirt);
		world.setBlock(i + 7, j + 0, k + 6, Blocks.dirt);
		world.setBlock(i + 7, j + 0, k + 7, Blocks.dirt);
		world.setBlock(i + 7, j + 0, k + 8, Blocks.grass);
		world.setBlock(i + 7, j + 1, k + 0, Blocks.air);
		world.setBlock(i + 7, j + 1, k + 1, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 7, j + 1, k + 2, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 1, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 1, k + 4, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 1, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 1, k + 6, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 1, k + 7, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 7, j + 1, k + 8, Blocks.air);
		world.setBlock(i + 7, j + 2, k + 0, Blocks.air);
		world.setBlock(i + 7, j + 2, k + 1, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 7, j + 2, k + 2, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 2, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 2, k + 4, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 2, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 2, k + 6, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 2, k + 7, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 7, j + 2, k + 8, Blocks.air);
		world.setBlock(i + 7, j + 3, k + 0, Blocks.air);
		world.setBlock(i + 7, j + 3, k + 1, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 7, j + 3, k + 2, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 3, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 3, k + 4, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 3, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 3, k + 6, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 3, k + 7, WinterBlocks.candyCaneBlock);
		world.setBlock(i + 7, j + 3, k + 8, Blocks.air);
		world.setBlock(i + 7, j + 4, k + 0, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 7, j + 4, k + 1, WinterBlocks.candyCaneBlock, 4, 2);
		world.setBlock(i + 7, j + 4, k + 2, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 4, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 4, k + 4, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 4, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 4, k + 6, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 4, k + 7, WinterBlocks.candyCaneBlock, 4, 2);
		world.setBlock(i + 7, j + 4, k + 8, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 7, j + 5, k + 0, Blocks.air);
		world.setBlock(i + 7, j + 5, k + 1, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 7, j + 5, k + 2, Blocks.snow);
		world.setBlock(i + 7, j + 5, k + 3, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 5, k + 4, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 5, k + 5, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 5, k + 6, Blocks.snow);
		world.setBlock(i + 7, j + 5, k + 7, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 7, j + 5, k + 8, Blocks.air);
		world.setBlock(i + 7, j + 6, k + 0, Blocks.air);
		world.setBlock(i + 7, j + 6, k + 1, Blocks.air);
		world.setBlock(i + 7, j + 6, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 7, j + 6, k + 3, Blocks.snow);
		world.setBlock(i + 7, j + 6, k + 4, WinterBlocks.fruitCakeBricks);
		world.setBlock(i + 7, j + 6, k + 5, Blocks.snow);
		world.setBlock(i + 7, j + 6, k + 6, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 7, j + 6, k + 7, Blocks.air);
		world.setBlock(i + 7, j + 6, k + 8, Blocks.air);
		world.setBlock(i + 7, j + 7, k + 0, Blocks.air);
		world.setBlock(i + 7, j + 7, k + 1, Blocks.air);
		world.setBlock(i + 7, j + 7, k + 2, Blocks.air);
		world.setBlock(i + 7, j + 7, k + 3, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 7, j + 7, k + 4, Blocks.snow);
		world.setBlock(i + 7, j + 7, k + 5, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 7, j + 7, k + 6, Blocks.air);
		world.setBlock(i + 7, j + 7, k + 7, Blocks.air);
		world.setBlock(i + 7, j + 7, k + 8, Blocks.air);
		world.setBlock(i + 7, j + 8, k + 0, Blocks.air);
		world.setBlock(i + 7, j + 8, k + 1, Blocks.air);
		world.setBlock(i + 7, j + 8, k + 2, Blocks.air);
		world.setBlock(i + 7, j + 8, k + 3, Blocks.air);
		world.setBlock(i + 7, j + 8, k + 4, WinterBlocks.singleSnowSlab);
		world.setBlock(i + 7, j + 8, k + 5, Blocks.air);
		world.setBlock(i + 7, j + 8, k + 6, Blocks.air);
		world.setBlock(i + 7, j + 8, k + 7, Blocks.air);
		world.setBlock(i + 7, j + 8, k + 8, Blocks.air);
		world.setBlock(i + 7, j + 9, k + 0, Blocks.air);
		world.setBlock(i + 7, j + 9, k + 1, Blocks.air);
		world.setBlock(i + 7, j + 9, k + 2, Blocks.air);
		world.setBlock(i + 7, j + 9, k + 3, Blocks.air);
		world.setBlock(i + 7, j + 9, k + 4, Blocks.air);
		world.setBlock(i + 7, j + 9, k + 5, Blocks.air);
		world.setBlock(i + 7, j + 9, k + 6, Blocks.air);
		world.setBlock(i + 7, j + 9, k + 7, Blocks.air);
		world.setBlock(i + 7, j + 9, k + 8, Blocks.air);
		world.setBlock(i + 8, j + 0, k + 0, Blocks.grass);
		world.setBlock(i + 8, j + 0, k + 1, Blocks.grass);
		world.setBlock(i + 8, j + 0, k + 2, Blocks.grass);
		world.setBlock(i + 8, j + 0, k + 3, Blocks.grass);
		world.setBlock(i + 8, j + 0, k + 4, Blocks.grass);
		world.setBlock(i + 8, j + 0, k + 5, Blocks.grass);
		world.setBlock(i + 8, j + 0, k + 6, Blocks.grass);
		world.setBlock(i + 8, j + 0, k + 7, Blocks.grass);
		world.setBlock(i + 8, j + 0, k + 8, Blocks.grass);
		world.setBlock(i + 8, j + 1, k + 0, Blocks.air);
		world.setBlock(i + 8, j + 1, k + 1, Blocks.air);
		world.setBlock(i + 8, j + 1, k + 2, Blocks.air);
		world.setBlock(i + 8, j + 1, k + 3, Blocks.air);
		world.setBlock(i + 8, j + 1, k + 4, Blocks.air);
		world.setBlock(i + 8, j + 1, k + 5, Blocks.air);
		world.setBlock(i + 8, j + 1, k + 6, Blocks.air);
		world.setBlock(i + 8, j + 1, k + 7, Blocks.air);
		world.setBlock(i + 8, j + 1, k + 8, Blocks.air);
		world.setBlock(i + 8, j + 2, k + 0, Blocks.air);
		world.setBlock(i + 8, j + 2, k + 1, Blocks.air);
		world.setBlock(i + 8, j + 2, k + 2, Blocks.air);
		world.setBlock(i + 8, j + 2, k + 3, Blocks.air);
		world.setBlock(i + 8, j + 2, k + 4, Blocks.air);
		world.setBlock(i + 8, j + 2, k + 5, Blocks.air);
		world.setBlock(i + 8, j + 2, k + 6, Blocks.air);
		world.setBlock(i + 8, j + 2, k + 7, Blocks.air);
		world.setBlock(i + 8, j + 2, k + 8, Blocks.air);
		world.setBlock(i + 8, j + 3, k + 0, Blocks.air);
		world.setBlock(i + 8, j + 3, k + 1, Blocks.air);
		world.setBlock(i + 8, j + 3, k + 2, Blocks.air);
		world.setBlock(i + 8, j + 3, k + 3, Blocks.air);
		world.setBlock(i + 8, j + 3, k + 4, Blocks.air);
		world.setBlock(i + 8, j + 3, k + 5, Blocks.air);
		world.setBlock(i + 8, j + 3, k + 6, Blocks.air);
		world.setBlock(i + 8, j + 3, k + 7, Blocks.air);
		world.setBlock(i + 8, j + 3, k + 8, Blocks.air);
		world.setBlock(i + 8, j + 4, k + 0, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 8, j + 4, k + 1, Blocks.air);
		world.setBlock(i + 8, j + 4, k + 2, Blocks.air);
		world.setBlock(i + 8, j + 4, k + 3, Blocks.air);
		world.setBlock(i + 8, j + 4, k + 4, Blocks.air);
		world.setBlock(i + 8, j + 4, k + 5, Blocks.air);
		world.setBlock(i + 8, j + 4, k + 6, Blocks.air);
		world.setBlock(i + 8, j + 4, k + 7, Blocks.air);
		world.setBlock(i + 8, j + 4, k + 8, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 8, j + 5, k + 0, Blocks.air);
		world.setBlock(i + 8, j + 5, k + 1, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 8, j + 5, k + 2, Blocks.air);
		world.setBlock(i + 8, j + 5, k + 3, Blocks.air);
		world.setBlock(i + 8, j + 5, k + 4, Blocks.air);
		world.setBlock(i + 8, j + 5, k + 5, Blocks.air);
		world.setBlock(i + 8, j + 5, k + 6, Blocks.air);
		world.setBlock(i + 8, j + 5, k + 7, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 8, j + 5, k + 8, Blocks.air);
		world.setBlock(i + 8, j + 6, k + 0, Blocks.air);
		world.setBlock(i + 8, j + 6, k + 1, Blocks.air);
		world.setBlock(i + 8, j + 6, k + 2, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 8, j + 6, k + 3, Blocks.air);
		world.setBlock(i + 8, j + 6, k + 4, Blocks.air);
		world.setBlock(i + 8, j + 6, k + 5, Blocks.air);
		world.setBlock(i + 8, j + 6, k + 6, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 8, j + 6, k + 7, Blocks.air);
		world.setBlock(i + 8, j + 6, k + 8, Blocks.air);
		world.setBlock(i + 8, j + 7, k + 0, Blocks.air);
		world.setBlock(i + 8, j + 7, k + 1, Blocks.air);
		world.setBlock(i + 8, j + 7, k + 2, Blocks.air);
		world.setBlock(i + 8, j + 7, k + 3, WinterBlocks.snowStairs, 2, 2);
		world.setBlock(i + 8, j + 7, k + 4, Blocks.air);
		world.setBlock(i + 8, j + 7, k + 5, WinterBlocks.snowStairs, 3, 2);
		world.setBlock(i + 8, j + 7, k + 6, Blocks.air);
		world.setBlock(i + 8, j + 7, k + 7, Blocks.air);
		world.setBlock(i + 8, j + 7, k + 8, Blocks.air);
		world.setBlock(i + 8, j + 8, k + 0, Blocks.air);
		world.setBlock(i + 8, j + 8, k + 1, Blocks.air);
		world.setBlock(i + 8, j + 8, k + 2, Blocks.air);
		world.setBlock(i + 8, j + 8, k + 3, Blocks.air);
		world.setBlock(i + 8, j + 8, k + 4, WinterBlocks.singleSnowSlab);
		world.setBlock(i + 8, j + 8, k + 5, Blocks.air);
		world.setBlock(i + 8, j + 8, k + 6, Blocks.air);
		world.setBlock(i + 8, j + 8, k + 7, Blocks.air);
		world.setBlock(i + 8, j + 8, k + 8, Blocks.air);
		world.setBlock(i + 8, j + 9, k + 0, Blocks.air);
		world.setBlock(i + 8, j + 9, k + 1, Blocks.air);
		world.setBlock(i + 8, j + 9, k + 2, Blocks.air);
		world.setBlock(i + 8, j + 9, k + 3, Blocks.air);
		world.setBlock(i + 8, j + 9, k + 4, Blocks.air);
		world.setBlock(i + 8, j + 9, k + 5, Blocks.air);
		world.setBlock(i + 8, j + 9, k + 6, Blocks.air);
		world.setBlock(i + 8, j + 9, k + 7, Blocks.air);
		world.setBlock(i + 8, j + 9, k + 8, Blocks.air);
		ItemDoor.placeDoorBlock(world, i + 1, j + 1, k + 4, 0, WinterSpecialBlocks.decorDoor);
		world.setBlock(i + 1, j + 1, k + 4, WinterSpecialBlocks.decorDoor);
		world.setBlockMetadataWithNotify(i + 1, j + 2, k + 4, 8, 2);
		world.setBlockMetadataWithNotify(i + 5, j + 3, k + 3, 4, 2);

		return true;
	}
}