// Date: 11/19/2013 4:21:27 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package wintercraft.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOrnament extends ModelBase
{
  //fields
    ModelRenderer Base1;
    ModelRenderer Top1;
    ModelRenderer Hook1;
    ModelRenderer Hook2;
  
  public ModelOrnament()
  {
    textureWidth = 64;
    textureHeight = 32;
    
    Base1 = new ModelRenderer(this, 0, 12);
    Base1.addBox(0F, 0F, 0F, 5, 5, 5);
    Base1.setRotationPoint(-2F, 8F, -3F);
    Base1.setTextureSize(64, 32);
    Base1.mirror = true;
    setRotation(Base1, 0F, 0F, 0F);
    Top1 = new ModelRenderer(this, 0, 7);
    Top1.addBox(0F, 0F, 0F, 3, 1, 3);
    Top1.setRotationPoint(-1F, 13F, -2F);
    Top1.setTextureSize(64, 32);
    Top1.mirror = true;
    setRotation(Top1, 0F, 0F, 0F);
    Hook1 = new ModelRenderer(this, 7, 2);
    Hook1.addBox(0F, 0F, 0F, 1, 3, 1);
    Hook1.setRotationPoint(0F, 14F, -1F);
    Hook1.setTextureSize(64, 32);
    Hook1.mirror = true;
    setRotation(Hook1, 0F, 0F, 0F);
    Hook2 = new ModelRenderer(this, 3, 2);
    Hook2.addBox(0F, 0F, 0F, 1, 1, 1);
    Hook2.setRotationPoint(0F, 16F, 0F);
    Hook2.setTextureSize(64, 32);
    Hook2.mirror = true;
    setRotation(Hook2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base1.render(f5);
    Top1.render(f5);
    Hook1.render(f5);
    Hook2.render(f5);
  }
  
  public void render(float f5){
	  Base1.render(f5);
	  Top1.render(f5);
	  Hook1.render(f5);
	  Hook2.render(f5);
  }
  
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
