// Date: 11/6/2013 7:34:08 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package wintercraft.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMug extends ModelBase
{
  //fields
    ModelRenderer Base1;
    ModelRenderer Base2;
    ModelRenderer Base3;
    ModelRenderer MugWall1;
    ModelRenderer MugWall2;
    ModelRenderer MugWall3;
    ModelRenderer MugWall4;
    ModelRenderer Mugwall5;
    ModelRenderer Mugwall6;
    ModelRenderer Mugwall7;
    ModelRenderer Mugwall8;
    ModelRenderer MugHandle2;
    ModelRenderer MugHandle1;
    ModelRenderer MugHandle3;
    ModelRenderer MugCocoa1;
    ModelRenderer MugCocoa2;
    ModelRenderer MugCocoa3;
  
  public ModelMug()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Base1 = new ModelRenderer(this, 0, 22);
      Base1.addBox(0F, 0F, 0F, 5, 1, 9);
      Base1.setRotationPoint(-2F, -1F, -6F);
      Base1.setTextureSize(64, 32);
      Base1.mirror = true;
      setRotation(Base1, 0F, 0F, 0F);
      Base2 = new ModelRenderer(this, 0, 14);
      Base2.addBox(0F, 0F, 0F, 7, 1, 7);
      Base2.setRotationPoint(-3F, -1F, -5F);
      Base2.setTextureSize(64, 32);
      Base2.mirror = true;
      setRotation(Base2, 0F, 0F, 0F);
      Base3 = new ModelRenderer(this, 0, 8);
      Base3.addBox(0F, 0F, 0F, 9, 1, 5);
      Base3.setRotationPoint(-4F, -1F, -4F);
      Base3.setTextureSize(64, 32);
      Base3.mirror = true;
      setRotation(Base3, 0F, 0F, 0F);
      MugWall1 = new ModelRenderer(this, 29, 0);
      MugWall1.addBox(0F, 0F, 0F, 5, 9, 1);
      MugWall1.setRotationPoint(-2F, -10F, 2F);
      MugWall1.setTextureSize(64, 32);
      MugWall1.mirror = true;
      setRotation(MugWall1, 0F, 0F, 0F);
      MugWall2 = new ModelRenderer(this, 41, 0);
      MugWall2.addBox(0F, 0F, 0F, 5, 9, 1);
      MugWall2.setRotationPoint(-2F, -10F, -6F);
      MugWall2.setTextureSize(64, 32);
      MugWall2.mirror = true;
      setRotation(MugWall2, 0F, 0F, 0F);
      MugWall3 = new ModelRenderer(this, 41, 10);
      MugWall3.addBox(0F, 0F, 0F, 1, 9, 5);
      MugWall3.setRotationPoint(-4F, -10F, -4F);
      MugWall3.setTextureSize(64, 32);
      MugWall3.mirror = true;
      setRotation(MugWall3, 0F, 0F, 0F);
      MugWall4 = new ModelRenderer(this, 29, 10);
      MugWall4.addBox(0F, 0F, 0F, 1, 9, 5);
      MugWall4.setRotationPoint(4F, -10F, -4F);
      MugWall4.setTextureSize(64, 32);
      MugWall4.mirror = true;
      setRotation(MugWall4, 0F, 0F, 0F);
      Mugwall5 = new ModelRenderer(this, 54, 10);
      Mugwall5.addBox(0F, 0F, 0F, 1, 9, 1);
      Mugwall5.setRotationPoint(3F, -10F, 1F);
      Mugwall5.setTextureSize(64, 32);
      Mugwall5.mirror = true;
      setRotation(Mugwall5, 0F, 0F, 0F);
      Mugwall6 = new ModelRenderer(this, 59, 10);
      Mugwall6.addBox(0F, 0F, 0F, 1, 9, 1);
      Mugwall6.setRotationPoint(-3F, -10F, 1F);
      Mugwall6.setTextureSize(64, 32);
      Mugwall6.mirror = true;
      setRotation(Mugwall6, 0F, 0F, 0F);
      Mugwall7 = new ModelRenderer(this, 54, 0);
      Mugwall7.addBox(0F, 0F, 0F, 1, 9, 1);
      Mugwall7.setRotationPoint(-3F, -10F, -5F);
      Mugwall7.setTextureSize(64, 32);
      Mugwall7.mirror = true;
      setRotation(Mugwall7, 0F, 0F, 0F);
      Mugwall8 = new ModelRenderer(this, 59, 0);
      Mugwall8.addBox(0F, 0F, 0F, 1, 9, 1);
      Mugwall8.setRotationPoint(3F, -10F, -5F);
      Mugwall8.setTextureSize(64, 32);
      Mugwall8.mirror = true;
      setRotation(Mugwall8, 0F, 0F, 0F);
      MugHandle2 = new ModelRenderer(this, 29, 25);
      MugHandle2.addBox(0F, 0F, 0F, 1, 1, 3);
      MugHandle2.setRotationPoint(0F, -4F, 3F);
      MugHandle2.setTextureSize(64, 32);
      MugHandle2.mirror = true;
      setRotation(MugHandle2, 0F, 0F, 0F);
      MugHandle1 = new ModelRenderer(this, 38, 25);
      MugHandle1.addBox(0F, 0F, 0F, 1, 1, 3);
      MugHandle1.setRotationPoint(0F, -8F, 3F);
      MugHandle1.setTextureSize(64, 32);
      MugHandle1.mirror = true;
      setRotation(MugHandle1, 0F, 0F, 0F);
      MugHandle3 = new ModelRenderer(this, 47, 25);
      MugHandle3.addBox(0F, 0F, 0F, 1, 3, 1);
      MugHandle3.setRotationPoint(0F, -7F, 5F);
      MugHandle3.setTextureSize(64, 32);
      MugHandle3.mirror = true;
      setRotation(MugHandle3, 0F, 0F, 0F);
      MugCocoa1 = new ModelRenderer(this, 0, 0);
      MugCocoa1.addBox(0F, 0F, 0F, 7, 1, 5);
      MugCocoa1.setRotationPoint(-3F, -8F, -4F);
      MugCocoa1.setTextureSize(64, 32);
      MugCocoa1.mirror = true;
      setRotation(MugCocoa1, 0F, 0F, 0F);
      MugCocoa2 = new ModelRenderer(this, 42, 30);
      MugCocoa2.addBox(0F, 0F, 0F, 5, 1, 1);
      MugCocoa2.setRotationPoint(-2F, -8F, -5F);
      MugCocoa2.setTextureSize(64, 32);
      MugCocoa2.mirror = true;
      setRotation(MugCocoa2, 0F, 0F, 0F);
      MugCocoa3 = new ModelRenderer(this, 29, 30);
      MugCocoa3.addBox(0F, 0F, 0F, 5, 1, 1);
      MugCocoa3.setRotationPoint(-2F, -8F, 1F);
      MugCocoa3.setTextureSize(64, 32);
      MugCocoa3.mirror = true;
      setRotation(MugCocoa3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base1.render(f5);
    Base2.render(f5);
    Base3.render(f5);
    MugWall1.render(f5);
    MugWall2.render(f5);
    MugWall3.render(f5);
    MugWall4.render(f5);
    Mugwall5.render(f5);
    Mugwall6.render(f5);
    Mugwall7.render(f5);
    Mugwall8.render(f5);
    MugHandle2.render(f5);
    MugHandle1.render(f5);
    MugHandle3.render(f5);
    MugCocoa1.render(f5);
    MugCocoa2.render(f5);
    MugCocoa3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
