// Date: 11/5/2013 9:33:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package wintercraft.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCandle extends ModelBase
{
  //fields
    ModelRenderer Candle;
    ModelRenderer Wick;
    ModelRenderer Candle2;
    ModelRenderer Candle3;
    ModelRenderer Candle4;
  
  public ModelCandle()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Candle = new ModelRenderer(this, 0, 3);
      Candle.addBox(0F, 0F, 0F, 3, 5, 3);
      Candle.setRotationPoint(0F, 0F, 0F);
      Candle.setTextureSize(64, 32);
      Candle.mirror = true;
      setRotation(Candle, 0F, 0F, 0F);
      Wick = new ModelRenderer(this, 13, 9);
      Wick.addBox(0F, 0F, 0F, 1, 1, 1);
      Wick.setRotationPoint(1F, 5F, 1F);
      Wick.setTextureSize(64, 32);
      Wick.mirror = true;
      setRotation(Wick, 0F, 0F, 0F);
      Candle2 = new ModelRenderer(this, 13, 6);
      Candle2.addBox(0F, 0F, 0F, 1, 1, 1);
      Candle2.setRotationPoint(0F, 0F, -1F);
      Candle2.setTextureSize(64, 32);
      Candle2.mirror = true;
      setRotation(Candle2, 0F, 0F, 0F);
      Candle3 = new ModelRenderer(this, 13, 3);
      Candle3.addBox(0F, 0F, 0F, 1, 1, 1);
      Candle3.setRotationPoint(-1F, 0F, 2F);
      Candle3.setTextureSize(64, 32);
      Candle3.mirror = true;
      setRotation(Candle3, 0F, 0F, 0F);
      Candle4 = new ModelRenderer(this, 13, 0);
      Candle4.addBox(0F, 0F, 0F, 1, 1, 1);
      Candle4.setRotationPoint(3F, 0F, 2F);
      Candle4.setTextureSize(64, 32);
      Candle4.mirror = true;
      setRotation(Candle4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Candle.render(f5);
    Wick.render(f5);
    Candle2.render(f5);
    Candle3.render(f5);
    Candle4.render(f5);
  }
  
  public void render(float f5){
	  Candle.render(f5);
	    Wick.render(f5);
	    Candle2.render(f5);
	    Candle3.render(f5);
	    Candle4.render(f5);

  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
