// Date: 10/18/2014 8:32:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package wintercraft.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSnowGlobe extends ModelBase
{
  //fields
	ModelRenderer GlobePillar1;
    ModelRenderer GlobePillar2;
    ModelRenderer GlobePillar3;
    ModelRenderer GlobePillar4;
    ModelRenderer GlobeTop1;
    ModelRenderer GlobeTop2;
    ModelRenderer GlobeTop3;
    ModelRenderer GlobeTop4;
    ModelRenderer GlobeFace1;
    ModelRenderer GlobeFace2;
    ModelRenderer GlobeFace3;
    ModelRenderer GlobeFace4;
    ModelRenderer GlobeFace5;
    ModelRenderer GlobeBottom;
    ModelRenderer BaseTop;
    ModelRenderer TreeTrunk;
    ModelRenderer TreeLeaves1;
    ModelRenderer TreeLeaves2;
    ModelRenderer CabinMain;
    ModelRenderer CabinRoof1;
    ModelRenderer CabinRoof2;
  
  public ModelSnowGlobe()
  {
    textureWidth = 128;
    textureHeight = 64;
    
    GlobePillar1 = new ModelRenderer(this, 0, 36);
    GlobePillar1.addBox(-7F, -11F, -7F, 1, 12, 1);
    GlobePillar1.setRotationPoint(0F, 21F, 0F);
    GlobePillar1.setTextureSize(128, 64);
    GlobePillar1.mirror = true;
    setRotation(GlobePillar1, 0.0174533F, 0F, 0F);
    GlobePillar2 = new ModelRenderer(this, 4, 36);
    GlobePillar2.addBox(6F, -11F, 6F, 1, 12, 1);
    GlobePillar2.setRotationPoint(0F, 21F, 0F);
    GlobePillar2.setTextureSize(128, 64);
    GlobePillar2.mirror = true;
    setRotation(GlobePillar2, 0.0174533F, 0F, 0F);
    GlobePillar3 = new ModelRenderer(this, 8, 36);
    GlobePillar3.addBox(-7F, -11F, 6F, 1, 12, 1);
    GlobePillar3.setRotationPoint(0F, 21F, 0F);
    GlobePillar3.setTextureSize(128, 64);
    GlobePillar3.mirror = true;
    setRotation(GlobePillar3, 0.0174533F, 0F, 0F);
    GlobePillar4 = new ModelRenderer(this, 12, 36);
    GlobePillar4.addBox(6F, -11F, -7F, 1, 12, 1);
    GlobePillar4.setRotationPoint(0F, 21F, 0F);
    GlobePillar4.setTextureSize(128, 64);
    GlobePillar4.mirror = true;
    setRotation(GlobePillar4, 0.0174533F, 0F, 0F);
    GlobeTop1 = new ModelRenderer(this, 16, 47);
    GlobeTop1.addBox(-6F, -12F, -6F, 12, 1, 1);
    GlobeTop1.setRotationPoint(0F, 21F, 0F);
    GlobeTop1.setTextureSize(128, 64);
    GlobeTop1.mirror = true;
    setRotation(GlobeTop1, 0.0174533F, 0F, 0F);
    GlobeTop2 = new ModelRenderer(this, 56, 51);
    GlobeTop2.addBox(-6F, -12F, -5F, 1, 1, 10);
    GlobeTop2.setRotationPoint(0F, 21F, 0F);
    GlobeTop2.setTextureSize(128, 64);
    GlobeTop2.mirror = true;
    setRotation(GlobeTop2, 0.0174533F, 0F, 0F);
    GlobeTop3 = new ModelRenderer(this, 16, 47);
    GlobeTop3.addBox(-6F, -12F, 5F, 12, 1, 1);
    GlobeTop3.setRotationPoint(0F, 21F, 0F);
    GlobeTop3.setTextureSize(128, 64);
    GlobeTop3.mirror = true;
    setRotation(GlobeTop3, 0.0174533F, 0F, 0F);
    GlobeTop4 = new ModelRenderer(this, 56, 51);
    GlobeTop4.addBox(5F, -12F, -5F, 1, 1, 10);
    GlobeTop4.setRotationPoint(0F, 21F, 0F);
    GlobeTop4.setTextureSize(128, 64);
    GlobeTop4.mirror = true;
    setRotation(GlobeTop4, 0.0174533F, 0F, 0F);
    GlobeFace1 = new ModelRenderer(this, 78, 40);
    GlobeFace1.addBox(-6F, -11F, -6F, 0, 12, 12);
    GlobeFace1.setRotationPoint(0F, 21F, 0F);
    GlobeFace1.setTextureSize(128, 64);
    GlobeFace1.mirror = true;
    setRotation(GlobeFace1, 0.0174533F, 0F, 0F);
    GlobeFace2 = new ModelRenderer(this, 78, 52);
    GlobeFace2.addBox(-6F, -11F, 6F, 12, 12, 0);
    GlobeFace2.setRotationPoint(0F, 21F, 0F);
    GlobeFace2.setTextureSize(128, 64);
    GlobeFace2.mirror = true;
    setRotation(GlobeFace2, 0.0174533F, 0F, 0F);
    GlobeFace3 = new ModelRenderer(this, 78, 40);
    GlobeFace3.addBox(6F, -11F, -6F, 0, 12, 12);
    GlobeFace3.setRotationPoint(0F, 21F, 0F);
    GlobeFace3.setTextureSize(128, 64);
    GlobeFace3.mirror = true;
    setRotation(GlobeFace3, 0.0174533F, 0F, 0F);
    GlobeFace4 = new ModelRenderer(this, 78, 52);
    GlobeFace4.addBox(-6F, -11F, -6F, 12, 12, 0);
    GlobeFace4.setRotationPoint(0F, 21F, 0F);
    GlobeFace4.setTextureSize(128, 64);
    GlobeFace4.mirror = true;
    setRotation(GlobeFace4, 0.0174533F, 0F, 0F);
    GlobeFace5 = new ModelRenderer(this, 93, 42);
    GlobeFace5.addBox(-5F, -12F, -5F, 10, 0, 10);
    GlobeFace5.setRotationPoint(0F, 21F, 0F);
    GlobeFace5.setTextureSize(128, 64);
    GlobeFace5.mirror = true;
    setRotation(GlobeFace5, 0.0174533F, 0.0174533F, 0F);
    GlobeBottom = new ModelRenderer(this, 0, 49);
    GlobeBottom.addBox(-7F, 1F, -7F, 14, 1, 14);
    GlobeBottom.setRotationPoint(0F, 21F, 0F);
    GlobeBottom.setTextureSize(128, 64);
    GlobeBottom.mirror = true;
    setRotation(GlobeBottom, 0.0174533F, 0.0174533F, 0F);
    BaseTop = new ModelRenderer(this, 0, 17);
    BaseTop.addBox(-7.5F, 1F, -7.5F, 15, 1, 15);
    BaseTop.setRotationPoint(0F, 22F, 0F);
    BaseTop.setTextureSize(128, 64);
    BaseTop.mirror = true;
    setRotation(BaseTop, 0.0174533F, 0F, 0F);
    TreeTrunk = new ModelRenderer(this, 67, 1);
    TreeTrunk.addBox(-5F, -5F, 3F, 2, 6, 2);
    TreeTrunk.setRotationPoint(0F, 21F, 0F);
    TreeTrunk.setTextureSize(128, 64);
    TreeTrunk.mirror = true;
    setRotation(TreeTrunk, 0.0174533F, 0.0174533F, 0F);
    TreeLeaves1 = new ModelRenderer(this, 67, 10);
    TreeLeaves1.addBox(-6F, -6F, 2F, 4, 1, 4);
    TreeLeaves1.setRotationPoint(0F, 21F, 0F);
    TreeLeaves1.setTextureSize(128, 64);
    TreeLeaves1.mirror = true;
    setRotation(TreeLeaves1, 0.0174533F, 0.0174533F, 0F);
    TreeLeaves2 = new ModelRenderer(this, 67, 16);
    TreeLeaves2.addBox(-5F, -7F, 3F, 2, 1, 2);
    TreeLeaves2.setRotationPoint(0F, 21F, 0F);
    TreeLeaves2.setTextureSize(128, 64);
    TreeLeaves2.mirror = true;
    setRotation(TreeLeaves2, 0.0174533F, 0.0174533F, 0F);
    CabinMain = new ModelRenderer(this, 67, 22);
    CabinMain.addBox(-1F, -3F, -5F, 6, 4, 6);
    CabinMain.setRotationPoint(0F, 21F, 0F);
    CabinMain.setTextureSize(128, 64);
    CabinMain.mirror = true;
    setRotation(CabinMain, 0.0174533F, 0.0174533F, 0F);
    CabinRoof1 = new ModelRenderer(this, 92, 25);
    CabinRoof1.addBox(0F, -4F, -5F, 4, 1, 6);
    CabinRoof1.setRotationPoint(0F, 21F, 0F);
    CabinRoof1.setTextureSize(128, 64);
    CabinRoof1.mirror = true;
    setRotation(CabinRoof1, 0.0174533F, 0.0174533F, 0F);
    CabinRoof2 = new ModelRenderer(this, 92, 15);
    CabinRoof2.addBox(1F, -5F, -5F, 2, 1, 6);
    CabinRoof2.setRotationPoint(0F, 21F, 0F);
    CabinRoof2.setTextureSize(128, 64);
    CabinRoof2.mirror = true;
    setRotation(CabinRoof2, 0.0174533F, 0.0174533F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    GlobePillar1.render(f5);
    GlobePillar2.render(f5);
    GlobePillar3.render(f5);
    GlobePillar4.render(f5);
    GlobeTop1.render(f5);
    GlobeTop2.render(f5);
    GlobeTop3.render(f5);
    GlobeTop4.render(f5);
    GlobeFace1.render(f5);
    GlobeFace2.render(f5);
    GlobeFace3.render(f5);
    GlobeFace4.render(f5);
    GlobeFace5.render(f5);
    GlobeBottom.render(f5);
    BaseTop.render(f5);
    TreeTrunk.render(f5);
    TreeLeaves1.render(f5);
    TreeLeaves2.render(f5);
    CabinMain.render(f5);
    CabinRoof1.render(f5);
    CabinRoof2.render(f5);
  }
  
  public void render(float f5){
	  GlobePillar1.render(f5);
	  GlobePillar2.render(f5);
	  GlobePillar3.render(f5);
	  GlobePillar4.render(f5);
	  GlobeTop1.render(f5);
	  GlobeTop2.render(f5);
	  GlobeTop3.render(f5);
	  GlobeTop4.render(f5);
	  GlobeFace1.render(f5);
	  GlobeFace2.render(f5);
	  GlobeFace3.render(f5);
	  GlobeFace4.render(f5);
	  GlobeFace5.render(f5);
	  GlobeBottom.render(f5);
	  BaseTop.render(f5);
	  TreeTrunk.render(f5);
	  TreeLeaves1.render(f5);
	  TreeLeaves2.render(f5);
	  CabinMain.render(f5);
	  CabinRoof1.render(f5);
	  CabinRoof2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
