// Date: 11/23/2013 11:12:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package wintercraft.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelPenguin extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer Beak;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer Tail;
    ModelRenderer LeftWing;
    ModelRenderer RightWing;
  
  public ModelPenguin()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 32);
      head.addBox(-3.5F, -8F, -2F, 7, 8, 4);
      head.setRotationPoint(0F, 7F, 1F);
      head.setTextureSize(128, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 45);
      body.addBox(-5F, -5F, -7F, 10, 6, 13);
      body.setRotationPoint(0F, 13F, 3F);
      body.setTextureSize(128, 64);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      Beak = new ModelRenderer(this, 7, 27);
      Beak.addBox(-1F, -3F, -4F, 2, 1, 2);
      Beak.setRotationPoint(0F, 7F, 1F);
      Beak.setTextureSize(128, 64);
      Beak.mirror = true;
      setRotation(Beak, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 10, 16);
      leg1.addBox(-1F, 0F, -1F, 2, 4, 2);
      leg1.setRotationPoint(-3F, 20F, 1F);
      leg1.setTextureSize(128, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 16);
      leg2.addBox(-1F, 0F, -1F, 2, 4, 2);
      leg2.setRotationPoint(3F, 20F, 1F);
      leg2.setTextureSize(128, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 30, 41);
      Tail.addBox(-1F, 0F, 0F, 2, 1, 1);
      Tail.setRotationPoint(0F, 18F, 4F);
      Tail.setTextureSize(128, 64);
      Tail.mirror = true;
      setRotation(Tail, 0F, 0F, 0F);
      LeftWing = new ModelRenderer(this, 14, 0);
      LeftWing.addBox(-1F, -1F, -2.5F, 1, 9, 5);
      LeftWing.setRotationPoint(-5F, 8F, 1F);
      LeftWing.setTextureSize(128, 64);
      LeftWing.mirror = true;
      setRotation(LeftWing, 0F, 0F, 0F);
      RightWing = new ModelRenderer(this, 0, 0);
      RightWing.addBox(0F, -1F, -2.5F, 1, 9, 5);
      RightWing.setRotationPoint(5F, 8F, 1F);
      RightWing.setTextureSize(128, 64);
      RightWing.mirror = true;
      setRotation(RightWing, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    head.render(f5);
    body.render(f5);
    Beak.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    Tail.render(f5);
    LeftWing.render(f5);
    RightWing.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
	  this.head.rotateAngleX = f5 / (180F / (float)Math.PI);
      this.head.rotateAngleY = f4 / (180F / (float)Math.PI);
      
      this.Beak.rotateAngleX = this.head.rotateAngleX;
      this.Beak.rotateAngleY = this.head.rotateAngleY;
	  
	  this.leg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5f;
	  this.leg1.rotateAngleY = 0.0f;
	  
	  this.leg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4f * f1;
	  this.leg2.rotateAngleY = 0.0f;
	  
	  this.LeftWing.rotateAngleZ = MathHelper.cos(0.6662F) * 2.0F * f1 * 0.5f;
	  this.LeftWing.rotateAngleX = 0.0f;
	  
	  this.RightWing.rotateAngleZ = MathHelper.cos( 0.6663F + (float)Math.PI) * 1.4f * f1;
	  this.RightWing.rotateAngleX = 0.0f;
  }

}
